### PR TITLE
Fix for updated `got` module

### PR DESCRIPTION
**Pull request by EuleHaken**
The options `retry` and `timeout` have to be of type object.
There are multiple options for timeout and retry, e.g. timeout can contain `request`, `lookup`, `connect` and so on. For more, read [this for retry](https://github.com/sindresorhus/got/blob/HEAD/documentation/7-retry.md#retry) and [this for timeout](https://github.com/sindresorhus/got/blob/HEAD/documentation/6-timeout.md) options.

I suppose, that just using `request: 123` for timeout should be fine.

See also: Supinic/supi-core#35

### CODE REVIEW

**Comment by EuleHaken** [comment]
Seems to run ok, however, commands where you make a `sb.Got` call, where you specifiy a `timeout` or `retry` have to be changed aswell.

**Comment by EuleHaken** [comment]
All commands, that would have had to be changed, should now be changed.

**Comment by EuleHaken** [comment]
Regarding the last commit (9b79dbfb26692b5b34746bac41c6e4a1efe6ba1f):

While locally testing, I found out that using `url: "..."` does not work, while `prefixUrl` works.
The error I received while using `url: "..."` looked something like this: `Uncaught RequestError: Missing "url" property`

**Review by Supinic — APPROVED** [review]
LGTM

**Pull request merged**
