### PR TITLE
Enhance roll command

### LINKED ISSUE #21: S#5430 - enhance the roll command with DnD syntax
[S#5430](https://supinic.com/data/suggestion/5430) by *ciomka202*

Enhance the `roll` command in its `DnD` style (e.g. `$roll 1d20`) to be able to parse simple operations, such as addition or subtraction - e.g. `$roll 1d20 - 5`. I'm not sure if multiplication should but included, I'll leave that to the author. Consider that the operations can be written both with and without whitespace, so string parsing could be necessary. Only allow one operation in a command.

As such, the `number` style of command invocation (e.g. `$roll 10 15`) should not be affected at all.

### PR DESCRIPTION
**Pull request by jprochazk**
Closes #21 

This implements a recursive descent parser for the DnD dice rolling notation. The parser produces an equivalent DnD expression but in the postfix form (also known as reverse polish notation) as its output. A stack-based interpreter then executes this form, similarly to a bytecode virtual machine.

Many words to say that now you can do `$roll 5d6 + 10` in a robust way. The parser is O(N), and so it should be more than fast enough. I also tried to document the behavior of everything in the code, which will hopefully make this easy to review.

A few notes:
* Error handling is a bit of a problem... Currently, I handle it by just redirecting to the `$help roll` command when the user does something wrong. I believe this is the best way, because the error handling is ambiguous. The problem is further described in the code.
* The lexer/parser/interpreter implementations are outside of the "Code" body in the command, because it's a lot of code. I wasn't sure where else to put it, but it is written independent of anything else (other than `sb.Utils.random`, but that can also be changed), so it should be easy to move it somewhere else.
* I'm not sure about testing, but the implementation only depends on `sb.Utils.random`, which can easily be mocked, so testing should also be pretty simple. I put some sample test values and their expected results at the very top of the file.

### CODE REVIEW

**Review by Supinic — CHANGES_REQUESTED** [review]
There's a lot of stuff here, so let's list it out:
- This much code pretty much warrants at least a `sb.Utils` method. I suggest creating a new PR in the `supi-core` repo and dumping of most of the code there. The method should probably have some sort of options, where we could set limits, and such.
- The parser should implement some sort of limits, as the rolls should be independent and if there's too many, could possibly brick the performance. Preivously, an arbitrary limit of `1e6` has been chosen. This is regarding the `roll_dice` method.
- There's a bunch of formatting issues, refer to other commands.
- All remaining code unrelated to the Utils method should be moved to command's `Static_Data` and used in the main body accordingly.

**Comment by jprochazk** [comment]
> * This much code pretty much warrants at least a `sb.Utils` method. I suggest creating a new PR in the `supi-core` repo and dumping of most of the code there. The method should probably have some sort of options, where we could set limits, and such.

I moved the underlying eval implementation into [it's own module](https://github.com/jprochazk/dice-roll-eval), and exposed it through `sb.Utils.evalDiceRoll` in supi-core. (https://github.com/Supinic/supi-core/pull/6)

> * The parser should implement some sort of limits, as the rolls should be independent and if there's too many, could possibly brick the performance. Preivously, an arbitrary limit of `1e6` has been chosen. This is regarding the `roll_dice` method.

The added sb.Utils method allows for specifying a maximum dice roll limit. In this PR, I set it to the previous `1.0e6`. (Can be seen [here](https://github.com/jprochazk/supibot-package-manager/blob/efc88ab6f9f98ef01b09f11e5ac71622a08da382/commands/roll/index.js#L41))

> * There's a bunch of formatting issues, refer to other commands.

I (hopefully) fixed the formatting issues. Most of it was caused by my IDE being set to format with 4 spaces instead of tabs.

> * All remaining code unrelated to the Utils method should be moved to command's `Static_Data` and used in the main body accordingly.

The `dice-roll-eval` implementation is fully self-contained, so it's now only a single function call in the command.

I also added full error handling. Users are now properly notified of any errors.

**Review by Supinic — APPROVED** [review]
LGTM

**Comment by Supinic** [comment]
Good work 👩‍🌾👍

**Pull request merged**
